env:
  browser: true
  es6: true
extends: ['eslint:recommended', 'plugin:react/recommended']
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    classes: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  no-console: 0
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
globals:
    chrome: true
    require: true
    module: true
